# Program-4 Implementation of ANN

* 2 layer fully connected NN
* input 2x1, hidden 3x1, output 1x1

In [1]:
import numpy as np

## Initilizing input and output

In [2]:
x = np.array([[2,9],[1,5],[3,6]],dtype=float)
y = np.array([[92],[86],[89]],dtype=float)
print(x,x.shape)
print(y,y.shape)

[[2. 9.]
 [1. 5.]
 [3. 6.]] (3, 2)
[[92.]
 [86.]
 [89.]] (3, 1)


## Normalize

* np.max(x) returns the max value when the parameter x is a array
* np.max(x,axis=0) returns the max value of each column, it'll be of size (1 x number_of_columns)
* normilization is done so that all the parameters are in the same scale here [0,1]

In [3]:
x = x/np.max(x,axis=0) 
y = y/100
print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


## Sigmoid Activation and Sigmoid Gradient

* Sigmoid is used as a activation fucntion here to add non-linearity in the network
* Gradient of sigmoid is used in Backpropagation step

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_grad(x):
    return x*(1-x)

## Hyper parameters initlization

* epoch is the one full forward and backward propagation of the whole input data
* eta(or alpha)is the learning rate, it decides how much of a step u take to find the optimal weight values for each epoch 

In [5]:
epoch = 1000
eta = 0.2

## Network Architecture



In [6]:
input_layer_neurons = 2
hidden_layer_neurons = 3
output_layer_neurons = 1

## Random Initilization of Weights and Baises

* Weigth value should always be random not zero as each neuron should calculate different values when they forward
* Bais values can be random or zeros
* wh,bh weight and bais from input layer to hidden layer
* wout,bout weight and bais from hidden layer to ouput layer 

In [7]:
wh = np.random.rand(input_layer_neurons,hidden_layer_neurons)
bh = np.zeros((1,hidden_layer_neurons))
wout = np.random.rand(hidden_layer_neurons,output_layer_neurons)
bout = np.zeros((1,output_layer_neurons))

## Forward and Backward propagation

In [8]:
for i in range(epoch):
    # Forward activations
    h_act = sigmoid(np.dot(x,wh)+bh)
    output = sigmoid(np.dot(h_act,wout)+bout)
    
    # Backward calculations of output layer
    Error_output = y - output
    output_grad = sigmoid_grad(output)
    delta_output = Error_output * output_grad
    
    # Backward calculations of hidden layer
    Error_hidden = np.dot(delta_output,wout.T)
    hidden_grad = sigmoid_grad(h_act)
    delta_hidden = Error_hidden * hidden_grad
    
    # Updating weights
    wh = wh + np.dot(x.T,delta_hidden)*eta
    wout = wout + np.dot(h_act.T,delta_output)*eta

## Comparision of actual and calculated outputs

In [9]:
print("\n\n Actual Output \n\n", y)
print("\n\n Predicted Output \n\n", output)



 Actual Output 

 [[0.92]
 [0.86]
 [0.89]]


 Predicted Output 

 [[0.89842706]
 [0.86568511]
 [0.90607851]]


'pwd' is not recognized as an internal or external command,
operable program or batch file.
