# Palindrome Program
> For any value (number, string, etc.)

In [8]:
# function which return reverse of a string
def reverse(s):
    return s[::-1]
 
def isPalindrome(s):
    # Calling reverse function
    rev = reverse(s)
 
    # Checking if both string are equal or not
    if (s == rev):
        return True
    return False
 
 
# Driver code
s = input("Enter something: ")
ans = isPalindrome(s)
 
if ans == 1:
    print("Yes")
else:
    print("No")

Enter something: 123454321
Yes


# Factorial
> Only for integers.

In [10]:
def fact(n):
    fact = 1
    for i in range(2, n+1):
        fact *= i
    return fact
try:
    x = int(input("Enter a number: "))
    print(fact(x))
except:
    print("Some Error.")

Enter a number: 123
12146304367025329675766243241881295855454217088483382315328918161829235892362167668831156960612640202170735835221294047782591091570411651472186029519906261646730733907419814952960000000000000000000000000000


In [45]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [46]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.95167977 0.77059165]
 [0.38300141 0.82272443]]


# .csv File Ops
> - Input matrix from user and enter into a .csv file
> - Print contents of .csv file in matrix form

In [28]:
def writeCsv(data):
    try:
        filename = input("Enter filename: ")
        fh = open(filename, 'w')
        with myFile:
            writer = csv.writer(fh)
            writer.writerows(data)
        print("Writing complete")
    except:
        print("Some Error.")

In [71]:
import csv
import numpy
def readCsv():
#     try:
#         filename = input("Enter filename")
        filename = '2.csv'
        with open(filename, 'r') as csvFile:
            reader = csv.reader(csvFile)
            lines = np.array(list(reader))
            r,c = lines.shape
            h = np.zeros(c,)
            if lines[0,4] == 'no':
                lines[0] = h
                lines[0,4] = 'no'
            if lines[0,4] == 'yes':
                h = lines[0]
            
            for row in range(1,r):
                if lines[row, 4] == 'no':
                    lines[row] = h
                if lines[row, 4] == 'yes':
                    for i in range(len(lines[row])):
                        if h[i] is not lines[row, i]:
                            h[i] = str('?')
                    h = lines[row]
            for row in lines:
                print(row[0:4])
        csvFile.close()
#     except:
#         print("Some Error.")
readCsv()

ValueError: could not convert string to float: '?'

# Nearest Palindrome
- Input: N (0 <= N <= 10^14)
- Output: The nearest palindrome to the given N. If N is a palindrome, then output N.
- If the difference between the two nearest palindrome is the closest, output is the lower value.

In [51]:
# n = input("Enter a num")
# n = '123456678'
n = '1070'
l = len(n)
h1, h2 = n[:l//2], n[(l+1)//2:]
h3 = n[:(l+1)//2]
n1 = str(h1[:-1])+h1[::-1]
n1 = int(n1)
n2 = str(int(h1) - 1)
n2 += h1[::-1][1:]
print(h1,'\t',h2, '\t', n1, '\t', n2)

10 	 70 	 101 	 91
