In [1]:
import numpy as np

In [6]:
weights = np.mat(np.eye((16)))

In [4]:
np.shape(weights)


(16, 16)

In [11]:
ex = np.array([[1], [2], [3]])

In [12]:
ex

array([[1],
       [2],
       [3]])

In [13]:
print(ex)

[[1]
 [2]
 [3]]


In [14]:
np.shape(ex)

(3, 1)

In [15]:
ex1 = [1,2,3]

In [16]:
ex1a = np.array(ex1)

In [17]:
ex1a

array([1, 2, 3])

In [18]:
np.shape(ex1a)

(3,)